sudo: false
language: java
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  - WINWIN_DB_HOST=localhost WINWIN_DB_NAME=winwindb WINWIN_DB_USER=winwindbuser WINWIN_DB_PASSWORD=winwindbpassword
jdk:
  - openjdk10
services:
    - postgresql
before_script:
  - psql -c "CREATE DATABASE winwindb;"
  - psql -c "CREATE USER winwindbuser WITH ENCRYPTED PASSWORD 'winwindbpassword';"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE winwindb TO winwindbuser;"
