sudo: false
language: java
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  - WINWIN_DB_HOST=localhost WINWIN_DB_NAME=winwindb WINWIN_DB_USER=winwindbuser WINWIN_DB_PASSWORD=winwindbpassword WINWIN_DB_PORT=5433
jdk:
  - openjdk10
services:
    - postgresql
before_script:
  - psql --port=$WINWIN_DB_PORT -c "CREATE DATABASE winwindb;"
  - psql --port=$WINWIN_DB_PORT -c "CREATE USER winwindbuser WITH ENCRYPTED PASSWORD 'winwindbpassword';"
  - psql --port=$WINWIN_DB_PORT -c "GRANT ALL PRIVILEGES ON DATABASE winwindb TO winwindbuser;"
  - sed -i 's/5432/'"$WINWIN_DB_PORT"'/g' ./src/main/resources/application.properties
